[package]
name = "valid-perfect-square"
version = "0.1.0"
authors = ["fengkx <liangkx8237@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"